name = "NMRSpectraSimulator"
uuid = "2e4b1986-80aa-49f9-97f8-0783739fb47a"
authors = ["Roy <rwang013@uottawa.ca> and contributors"]
version = "0.2.0"

[deps]
GISSMOReader = "fab8f492-3bcc-4cb4-9708-3e824b5a8279"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
